### ISSUE TITLE
Shouldn't checkout master branch

### ISSUE THREAD

**Issue by JemarJones** [mixmaxhq/deyarn#2]
I was just browsing through your readme and noticed that the command checks out the master branch before starting the process. This enforces a branching model on users unnecessarily. For those using a branching model such as GitFlow, checking out master would mean basing the changes on production code, rather than the develop branch.

I suggest that instead the tool simply branch off of whatever the current branch is, leaving the choice of branching model up to the user.

**Comment by wearhere** [comment]
Checking out `master` before starting the process is designed to ensure that, when you submit the PR for these changes (from the tool-created `deyarnify` branch, to your default branch), the PR doesn't contain changes unrelated to deyarning.

I can understand that your default branch may not be `master`—but wouldn't the tool still need to switch to that other default branch, rather than branching from the current branch? So the tool would require a new option like `deyarn [-b <default branch>]`?

Anyhow we'd be willing to look at a PR to make such a change.

**Comment by JemarJones** [comment]
I can see the reasoning behind having the tool change branches, but in my opinion ensuring that you are on the correct branch when making changes should be the concern of the developer rather than the tool.

My only other thought about adding an option for default branch is that it creates a bit of an awkward experience if for example, the developer has already switched to their default branch, and now has to remember/know to specify the branch to the tool to avoid branching off of the wrong branch.

And awesome, I can make a PR sometime over this weekend most likely.

**Comment by lukebarton** [comment]
I agree with the OP. This tool needn't do anything with `git` at all - I just want to remove `yarn` and prepare for `npm`6.

**Comment by lukebarton** [comment]
Submitted a PR - https://github.com/mixmaxhq/deyarn/pull/6

**Comment by lukebarton** [comment]
As of 1.0.2 it no longer performs any git operations 🎉
