### ISSUE TITLE
engines.yarn must return valid semver syntax

### ISSUE THREAD

**Issue by acconrad** [mixmaxhq/deyarn#7]
Hi! We were using your package to help move us off of yarn and onto NPM. Our node app failed to deploy because the [`engines.yarn` line is invalid](https://github.com/mixmaxhq/deyarn/blob/master/src/index.js#L54). You can only provide a valid SEMVER string here, otherwise this will break deploys.

The solution here is to remove that path, rather than modify it. Oddly enough, `edit-json-file` doesn't have an option for `unset`-ing a line, so [I added it](https://github.com/IonicaBizau/edit-json-file/pull/12). You can pull from [my fork](https://github.com/acconrad/edit-json-file) to add this functionality in now if you'd like. I'm also going to create a pull request momentarily that will include the proposed fix.

**Comment by wearhere** [comment]
> Our node app failed to deploy because the engines.yarn line is invalid. You can only provide a valid SEMVER string here, otherwise this will break deploys.

Curious, what component/system is processing this and failing? As far as I knew, only the package managers read that, when installing using the corresponding engine—so if you weren't using yarn (as the message directs), then you would be fine (this is how it works for us).

**Comment by wearhere** [comment]
Does removing `engines.yarn` have the same effect as giving it an invalid semver string in the sense of prohibiting installation using yarn?

**Comment by acconrad** [comment]
@wearhere as I mentioned in the PR, this is failing with the plugin `edit-json-file` because it doesn't allow you to `unset` something, so you have to `set` it to `undefined` to essentially do the same thing. But basically the value you're placing in that key is not a valid value, it needs to be a SEMVER-formatted number

**Comment by wearhere** [comment]
@acconrad by
> this is failing with the plugin edit-json-file because it doesn't allow you to unset something, so you have to set it to undefined to essentially do the same thing

it seems you're saying that https://github.com/mixmaxhq/deyarn/pull/11/files#diff-1fdf421c05c1140f6d71444ea2b27638L54 would fail. This is curious since it did not fail for us at Mixmax when we last used this tool. Anyhow if that is throwing an error for you I would like to fix that for sure.

I do want to make sure that your new change, https://github.com/mixmaxhq/deyarn/pull/11/files#diff-1fdf421c05c1140f6d71444ea2b27638R54, is [functionally equivalent](https://github.com/mixmaxhq/deyarn/issues/7#issuecomment-426756078):

> Does removing engines.yarn have the same effect as giving it an invalid semver string in the sense of prohibiting installation using yarn?

That is, if you run deyarn on a project, publish a new version, and then try to install that version using yarn, it is supposed to fail. Perhaps this failure is what you're seeing in your deploys—are your deploys still using yarn? And if so, is that desirable?

When we deyarned, we did it everywhere, all at once, including in our deploy systems. Our intention behind making `engines.yarn` invalid in this way was to notify developers who were still using yarn that they needed to switch to npm.

**Comment by acconrad** [comment]
> it seems you're saying that mixmaxhq/deyarn/pull/11/files#diff-1fdf421c05c1140f6d71444ea2b27638L54 would fail. This is curious since it did not fail for us at Mixmax when we last used this tool. Anyhow if that is throwing an error for you I would like to fix that for sure.

Yes correct! In fact the way I discovered this bug in the first place was because it was set to an invalid value. If we keep it, others won't be able to run `deyarn`.

> are your deploys still using yarn? And if so, is that desirable?

No and no. If our point is to move off of yarn, we certainly want to make sure this package runs completely.

I believe that if this isn't merged, others will not be able to use this package.

**Comment by wearhere** [comment]
Ok @acconrad can you give me a specific set of steps to repro this problem? Like

```
1. check out <test npm package using yarn that you've created>
2. run deyarn

Expected result: deyarn ran without error
Actual result: you get error ...
```

**Comment by acconrad** [comment]
@wearhere tbh I can't since this is with a previous client, but it is a well known fact that [package.json files require valid semver structure for values on package keys](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tools/package_json#Key_reference)

**Comment by wearhere** [comment]
@acconrad,
>  it is a well known fact that package.json files require valid semver structure for values on package version keys

is certainly true if ever the field is read / used, but I do not believe that `engines.yarn` should ever be read unless yarn is used to install the package—which is what the invalid value is designed to prevent. https://github.com/mixmaxhq/rollup-plugin-root-import is an example: that was deyarned using this package, resulting in the invalid value being [written to its `package.json`](https://github.com/mixmaxhq/rollup-plugin-root-import/blob/0e591385d9e80c1b1925116d988d164c40461ad8/package.json#L42). Then, if you run the following commands

```sh
mkdir test
cd test
npm init -y
yarn add rollup-plugin-root-import
npm install rollup-plugin-root-import
```

you will see the following output, indicating that the package is fine to install with npm, just not yarn:

![image](https://user-images.githubusercontent.com/110000/50610006-4787cf00-0e86-11e9-8dc0-45ffe030eff1.png)

I also tested deyarn against https://github.com/mixmaxhq/rollup-plugin-root-import/commit/5cc8afde02cfbe20b7f188f4f32ec09ae9c0278a, i.e. just prior to deyarning, and `deyarn` ran fine.

So, thank you for the report, but unless you can repro the error, I am loathe to merge #11 since that would mean sacrificing the feature of this project where it prevents use of yarn after running. Closing this, but glad to reopen given further information.

**Comment by acconrad** [comment]
> sacrificing the feature of this project where it prevents use of yarn after running

How does this prevent the use of yarn after running? All it's doing is setting the json value to something valid so it can complete the `deyarn` script.

**Comment by wearhere** [comment]
The desired result is for `yarn add rollup-plugin-root-import` to fail (after `rollup-plugin-root-import` had been deyarned), as shown in [the screenshot above](https://github.com/mixmaxhq/deyarn/issues/7#issuecomment-450971444). I think that only happens because yarn reads the invalid value from `engines.yarn`; having #11 unset `engines.yarn` would break this.

> All it's doing is setting the json value to something valid so it can complete the deyarn script.

Btw as I noted [above](https://github.com/mixmaxhq/deyarn/issues/7#issuecomment-450971444), the deyarn script completes for me even without #11.

**Comment by acconrad** [comment]
Cool! Makes sense; I will need `deyarn` for future client projects so if I do run into issues I'll be sure to bring this up again. Thanks for looking into this and commenting!
